### ISSUE TITLE
Via could use nvmrc

### ISSUE THREAD

**Issue by RacyMind** [Sopamo/via#6]
It'd be useful when you use nvm for your projects

**Comment by fieteboerner** [comment]
thanks for your feedback.

Via is designed to execute very generic cli commands so it does not have any specific tooling logic at all. 

As of today you could execute your shell with its configuration to load and use nvm.
The configuration in my personal project looks like this:
```yaml
actions:
  ...
  watch: zsh -c "source ~/.zshrc && nvm use && npm run watch"
```

If you have any ideas in how to integrate this in an abstract manner, feel free to reopen this one.
